// Generated by CoffeeScript 1.4.0
(function() {
  var $canvas, Game, Round, main, rounds;

  rounds = [
    {
      tiles: ['http://i.imgur.com/ICn6oM3b.jpg', 'http://i.imgur.com/9JdVHQOb.jpg', 'http://i.imgur.com/FIUY1Fjb.jpg', 'http://i.imgur.com/8yxtHpvb.jpg'],
      correct: [0, 2],
      success: 'You won!'
    }
  ];

  Game = (function() {

    function Game() {
      this.rounds = [];
    }

    Game.prototype.addRound = function(round) {
      return this.rounds.push(round);
    };

    return Game;

  })();

  Round = (function() {

    function Round(data) {
      this.tiles = data.tiles;
      this.correct = data.correct;
      this.success = data.success;
    }

    Round.prototype.display = function() {
      var $tile, idx, tile, _i, _len, _ref, _results;
      $canvas.empty();
      _ref = this.tiles;
      _results = [];
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        tile = _ref[idx];
        $tile = $("<img src='" + tile + "'>");
        if (this.correct.indexOf(idx) !== -1) {
          $tile.addClass('correct');
        }
        $tile.appendTo($canvas);
        _results.push(console.log(tile, idx));
      }
      return _results;
    };

    return Round;

  })();

  $canvas = $('#canvas');

  main = function() {
    var g, r, round, _i, _len, _results;
    g = new Game();
    _results = [];
    for (_i = 0, _len = rounds.length; _i < _len; _i++) {
      round = rounds[_i];
      r = new Round(round);
      g.addRound(r);
      _results.push(r.display());
    }
    return _results;
  };

  $(main);

}).call(this);
